// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ1BR_ZSuaoM6g9oH7QIPp-pkQN01q4Cw',
    appId: '1:697219972281:web:b9fa6b0339b1e84fcd2f68',
    messagingSenderId: '697219972281',
    projectId: 'chatapp-90d07',
    authDomain: 'chatapp-90d07.firebaseapp.com',
    storageBucket: 'chatapp-90d07.firebasestorage.app',
    measurementId: 'G-C3Y7V1Y8ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc2Lgf_OmJOxnb2z4dghS2j1y2v__kfOI',
    appId: '1:697219972281:android:62ebc4fb97fbf5b3cd2f68',
    messagingSenderId: '697219972281',
    projectId: 'chatapp-90d07',
    storageBucket: 'chatapp-90d07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTXielvhEgXAh471YafIxfFWFG-W6Ankg',
    appId: '1:697219972281:ios:299abca8f625dc46cd2f68',
    messagingSenderId: '697219972281',
    projectId: 'chatapp-90d07',
    storageBucket: 'chatapp-90d07.firebasestorage.app',
    iosBundleId: 'com.example.chat2',
  );
}
